# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CTSM Mini-tutorial 2022
author: Negin Sobhani, Danica Lombardozzi, Adrianna Foster, Will Wieder
logo: images/ncar_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
#execute:
#  execute_notebooks: force

execute:
  execute_notebooks: 'off'


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: tutorial_book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/NCAR/CTSM-Tutorial-2022  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_edit_page_button : true
  use_issues_button    : true
  home_page_in_navbar  : false


launch_buttons:
  binder             : true
  binderhub          : true
  binderhub_url: https://mybinder.org
  jupyterhub         : false
  thebe              : false
  colab              : false


# Launch button settings
#launch_buttons:
#  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
#  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
#  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
#  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
#  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)
